# Generated by Django 5.1.3 on 2024-11-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depreciation', '0002_rename_userinput_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_price', models.IntegerField()),
                ('highest_value', models.IntegerField()),
                ('lowest_value', models.IntegerField()),
            ],
        ),
    ]
