# Generated by Django 5.1.3 on 2025-02-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depreciation', '0004_vehicle_transmission_vehicle_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='highest_value',
            new_name='depreciation',
        ),
        migrations.RemoveField(
            model_name='value',
            name='lowest_value',
        ),
        migrations.RemoveField(
            model_name='value',
            name='value_price',
        ),
    ]
