# Generated by Django 5.1.3 on 2024-11-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depreciation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInput',
            new_name='Vehicle',
        ),
    ]
