# Generated by Django 5.1.3 on 2024-11-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depreciation', '0003_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(default='manual', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
